name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.buildsystem }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        buildsystem: [cmake] #[bazel, cmake]
        os: [ubuntu-18.04] #[macOS-latest, ubuntu-18.04, windows-2019]
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: .github/scripts/run-${{ matrix.buildsystem }}-prepare ${{ matrix.os }}
      - name: Test
        run: .github/scripts/run-${{ matrix.buildsystem }}-test ${{ matrix.os }}
