name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.buildsystem }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        buildsystem: [cmake] #[bazel, cmake]
        os: [ubuntu-18.04] #[macOS-latest, ubuntu-18.04, windows-2019]
    steps:
      - uses: actions/checkout@main
      #- uses: lukka/get-cmake@latest

      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@v3.2
        id: runvcpkg
        with:
          vcpkgArguments: 'benchmark function2 gtest prometheus-cpp boost-asio boost-callable-traits boost-chrono boost-hana boost-optional boost-mp11 boost-thread boost-variant2'
          vcpkgTriplet: 'x64-linux'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: 'c7ab9d3110813979a873b2dbac630a9ab79850dc' # 2020.04

      - name: 'Build asyncly'
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          #cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          #cmakeListsTxtPath: '${{ github.workspace }}/cmakesettings.json/CMakeLists.txt'
          cmakeBuildType: 'Release'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ runner.workspace }}/cmakebuild'
          #cmakeAppendedArgs: '-GNinja'

      - name: 'Test asyncly'
        run: |
          cd "${{ runner.workspace }}/cmakebuild"
          ctest -C Release -V
      #- name: Prepare
      #  run: .github/scripts/run-${{ matrix.buildsystem }}-prepare ${{ matrix.os }}
      #- name: Test
      #  run: .github/scripts/run-${{ matrix.buildsystem }}-test ${{ matrix.os }}
